### ISSUE TITLE
router与controller方法关联设计上显得有一点分裂

### ISSUE THREAD

**Issue by Garfield-yin** [open-node/open-router#1]
router与controller方法关联设计上显得有一点分裂，具体表现为：

这种写法增加路由时：
r.resource('public_opinion');

controller中文件命名必须为public_opinion.js才能识别

而当使用这种写法时：
r.post('/public_opinions/:publicOpinionId/accounts', 'publicOpinionAccount#addAccount');

controller中文件命名必须为:public-opinion-account.js

建议不管使用什么写法，controller中文名命名方式均保持统一，或者‘-’‘_’两种文件命名方式均支持

**Comment by zhaoxiongfei** [comment]
这个是open-rest当初定义的命名规范，文件名用中划线分隔，在加载的时候对应的名称会处理成驼峰式的。所以这里是一个个小小的约定。
